name: Run Linting

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Flake8 Linting
      run: |
        flake8 .

    - name: Black Formatting Check
      run: |
        black --check .

    - name: Check for unstaged changes after Black
      run: |
        git diff --exit-code
